// Player + compositor for "The Last Berry Mochi". Timing comes from assets/cues.json,
// mouths from assets/lipsync.json, sound from assets/mix.wav (all generated by tools/make_audio.py).
import * as THREE from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { W, H, clamp } from './kit.js';
import { build } from './film.js';

const out = document.getElementById('out'), ctx = out.getContext('2d'), audio = document.getElementById('mix');
const F = '"Fredoka", system-ui, sans-serif';

const renderer = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true });
renderer.setPixelRatio(1); renderer.setSize(W, H, false);
renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.toneMapping = THREE.NeutralToneMapping;
const env = new THREE.PMREMGenerator(renderer).fromScene(new RoomEnvironment(), 0.04).texture;

await document.fonts.load(`700 40px ${F}`);
const [cues, lipsync] = await Promise.all(['assets/cues.json', 'assets/lipsync.json'].map((u) => fetch(u).then((r) => r.json())));
const film = build({ lipsync, cues: cues.cues });
const DURATION = cues.duration;
film.scene.environment = env;

function renderAt(T) {
  T = clamp(T, 0, DURATION - 1e-3);
  film.update(T);
  renderer.render(film.scene, film.camera);
  ctx.drawImage(renderer.domElement, 0, 0, W, H);
  film.overlay(ctx, T, F);
}
film.update(0); renderer.compile(film.scene, film.camera);

// ---------- player ----------
const ui = { play: document.getElementById('play'), scrub: document.getElementById('scrub'), time: document.getElementById('time'), rec: document.getElementById('rec') };
ui.scrub.max = DURATION;
let t = 0;
const fmt = (s) => `${Math.floor(s / 60)}:${(s % 60).toFixed(1).padStart(4, '0')}`;
function show() { renderAt(t); ui.scrub.value = t; ui.time.textContent = `${fmt(t)} / ${fmt(DURATION)}`; }
function loop() { if (audio.paused) return; t = audio.currentTime; show(); requestAnimationFrame(loop); }
audio.onplay = () => { ui.play.textContent = '❚❚'; requestAnimationFrame(loop); };
audio.onpause = audio.onended = () => { ui.play.textContent = '▶'; stopRec(); };
ui.play.onclick = () => { if (audio.paused) { if (audio.currentTime >= DURATION - 0.05) audio.currentTime = 0; audio.play(); } else audio.pause(); };
ui.scrub.oninput = () => { t = +ui.scrub.value; audio.currentTime = t; show(); };
addEventListener('keydown', (e) => { if (e.code === 'Space') { e.preventDefault(); ui.play.click(); } });

let rec = null;
function stopRec() { if (rec) { rec.stop(); rec = null; ui.rec.textContent = '● Record'; } }
ui.rec.onclick = () => {
  if (rec) return stopRec();
  const stream = out.captureStream(30);
  try { (audio.captureStream?.() || audio.mozCaptureStream?.()).getAudioTracks().forEach((tr) => stream.addTrack(tr)); } catch {}
  const chunks = []; rec = new MediaRecorder(stream, { mimeType: 'video/webm;codecs=vp9,opus', videoBitsPerSecond: 12e6 });
  rec.ondataavailable = (e) => chunks.push(e.data);
  rec.onstop = () => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(chunks, { type: 'video/webm' })); a.download = 'berry-heist.webm'; a.click(); };
  audio.currentTime = 0; rec.start(); ui.rec.textContent = '■ Stop'; audio.play();
};

window.__duration = DURATION;
window.__seek = (time) => renderAt(time);

const q = new URLSearchParams(location.search);
t = +(q.get('t') || 0); audio.currentTime = t; show();
window.__ready = true;
