"""The Last Berry Mochi: beat sheet (story order). Build: python audio/build.py berry-heist"""
from build import Sheet

sheet = Sheet(
    rate_k=1.5, gap_scale=0.55, mark_scale=0.55,
    keep={'silence2', 's6', 'cut_lumi', 'lumi_stare', 'black', 'silence3'},       # comic silences keep full length
    silences=['silence2', 's6', 'cut_lumi', 'lumi_stare', 'black'],              # room tone drops out
)

# SCENE 1 — top-secret mission (corridor, night)
sheet.mark('s1', 1.8)
sheet.vo('milo_target', 'milo', 'Target is twelve meters ahead.', whisper=True, gap=0.1)
sheet.mark('pip_looks', 0.6, gap=0.15)
sheet.vo('pip_twelve', 'pip', 'Twelve?')
sheet.vo('milo_never', 'milo', 'Never question the mission.', whisper=True, gap=0.35)
sheet.mark('milo_points', 0.9, gap=0.1)
sheet.vo('milo_last', 'milo', '<prosody rate="85%">The last Berry Mochi.</prosody>', whisper=True)
sheet.fx('gulp', gap=0.2)
sheet.vo('pip_beautiful', 'pip', '<prosody rate="80%">So beautiful...</prosody>', gap=0.1)
sheet.vo('milo_focus', 'milo', 'Focus.', whisper=True, gap=0.2)
# SCENE 2 — super spy
sheet.mark('s2', 1.3, gap=0.3)                                    # Mimi & Moss peek, Milo backs up
sheet.vo('milo_3', 'milo', 'Three...')
sheet.vo('pip_2', 'pip', 'Two...', gap=0.15)
sheet.vo('mimi_1', 'mimi', '<prosody pitch="+20%">One!</prosody>', gap=0.15)
sheet.fx('whoosh', gap=0.05)
sheet.fx('ding', gap='@0.2')
sheet.fx('thud', gap='@0.5')
sheet.fx('skid', gap='@0.05')
sheet.fx('glasses_slide', gap='@0.55')
sheet.mark('silence2', 1.0, gap=0.2)
sheet.vo('pip_stealthy', 'pip', 'Very stealthy.')
sheet.vo('milo_thanks', 'milo', '<prosody rate="80%">...thank you.</prosody>', gap=0.4)
# SCENE 3 — LASER 9000
sheet.mark('s3', 0.8, gap=0.4)
sheet.vo('milo_pip', 'milo', 'Pip.')
sheet.vo('pip_waiting', 'pip', "I've been waiting my entire life for this.", gap=0.3)
sheet.fx('zip', gap=0.1)
sheet.mark('device_out', 0.7)
sheet.vo('moss_why', 'moss', 'Why nine thousand?', gap=0.2)
sheet.vo('pip_8000', 'pip', "Eight thousand wasn't enough.", gap=0.3)
sheet.mark('attach', 0.5, gap=0.1)
sheet.fx('beep')
sheet.fx('brrr', gap=0.05)
sheet.vo('pip_watch', 'pip', 'Watch this.', gap='@0.6')
sheet.fx('pop', gap=0.25)
sheet.fx('boing', gap='@0.04')
sheet.fx('slap', gap='@0.16')
sheet.mark('silence3', 1.0, gap=0.15)
sheet.vo('mimi_liked', 'mimi', 'I liked it.')
sheet.vo('pip_thankyou', 'pip', 'Thank you.', gap=0.3)
sheet.fx('zap', gap=0.3)
sheet.vo('laser_1', 'laser', "Pip's super secret laser! Pip is smart! Pip is handsome! Pip", gap=0.1)
sheet.vo('pip_nonono', 'pip', '<prosody rate="140%">No no no no no!</prosody>', gap='@2.1')
sheet.fx('bonk1', name='bonk', gap='@0.4')
sheet.fx('bonk2', name='bonk', gap='@0.35')
sheet.vo('laser_2', 'laser', '<prosody volume="+60%">Pip is very handsome!</prosody>', loud=True, gap=0.1)
sheet.mark('facepalm', 0.6, gap=0.1)
# SCENE 4 — Bobo solves it
sheet.mark('s4', 0.3, gap=0.2)
sheet.fx('sniff')
sheet.mark('bobo_looks', 1.2, gap=0.1)                            # lock → down → the little OPEN button
sheet.fx('click')
sheet.fx('ding2', gap='@0.25')
sheet.mark('turn_heads', 1.2, gap=0.3)
sheet.mark('bobo_sits', 0.6)
sheet.vo('moss_about', 'moss', '...I was about to suggest that.')
sheet.vo('milo_nope', 'milo', "No you weren't.", gap=0.3)
# SCENE 5 — the treasure
sheet.mark('s5', 0.3, gap=0.4)
sheet.fx('shimmer')
sheet.mark('push_mochi', 1.4, gap='@0.0')
sheet.vo('pip_rich', 'pip', '<prosody rate="85%">We\'re rich.</prosody>', whisper=False)
sheet.vo('mimi_one', 'mimi', "It's one mochi.", gap=0.3)
sheet.vo('pip_emo', 'pip', 'Emotionally rich.', gap=0.3)
sheet.mark('reach', 1.3, gap=0.2)
sheet.fx('lightswitch')
# SCENE 6 — Lumi
sheet.mark('s6', 3.0)                                      # three seconds of silence...
sheet.fx('buzz', gap='@0.0')                                      # ...except the Laser 9000
sheet.vo('laser_3', 'laser', '<prosody rate="70%">Pip is handsome...</prosody>', weak=True)
sheet.fx('bonk3', name='bonk', gap=0.25)
sheet.mark('withdraw', 0.9, gap=0.1)
sheet.vo('milo_lumi', 'milo', 'Lumi.')
sheet.vo('lumi_milo', 'lumi', 'Milo.', gap=0.35)
sheet.vo('milo_funny', 'milo', 'Funny story.', gap=0.35)
sheet.mark('lumi_scan', 0.7, gap=0.1)
sheet.vo('lumi_doubt', 'lumi', 'I doubt that.')
# SCENE 7 — the worst lie
sheet.vo('milo_security', 'milo', "We're performing a security inspection.", gap=0.35)
sheet.mark('lumi_looks', 2.6, gap=0.15)                           # Pip, laser, Mimi, the bag, Moss
sheet.vo('moss_plant', 'moss', "I'm<break time='300ms'/> a plant.")
sheet.fx('plop', gap=0.3)
sheet.mark('noreact', 0.9)
# SCENE 8 — RUN!
sheet.vo('lumi_five', 'lumi', "I'll give you five seconds.")
sheet.mark('milo_glance', 0.8, gap=0.1)
sheet.vo('milo_run', 'milo', '<prosody volume="+50%" pitch="+25%">RUN!</prosody>')
sheet.mark('slowmo', 4.2, gap=0.1)
sheet.fx('fwip1', name='fwip', gap='@0.2')
sheet.fx('softpoof', name='softpoof', gap='@0.8')
sheet.fx('tap1', name='tap', gap='@0.6')
sheet.vo('pip_uhoh', 'pip', 'Uh oh.', slow=True, gap='@0.5')
sheet.fx('snap', gap='@0.9')
sheet.fx('fwip2', name='fwip', gap='@0.6')
# SCENE 9 — total disaster (back to normal speed)
sheet.fx('crash', gap=0.9)
sheet.fx('boing2', name='boing', gap='@0.22')
sheet.fx('paper_poof', gap='@0.22')
sheet.fx('splash', gap='@0.22')
sheet.mark('chaos_end', 0.3)
# SCENE 10 — deadpan
sheet.mark('s10', 1.4, gap=0.2)
sheet.fx('nom1', name='nom'); sheet.fx('nom2', name='nom', gap=0.25); sheet.fx('nom3', name='nom', gap=0.25)
sheet.mark('bobo_stops', 1.1, gap=0.2)
sheet.fx('nom4', name='nom')
sheet.mark('cut_lumi', 1.8, gap=0.1)
sheet.vo('lumi_so', 'lumi', 'So...')
sheet.vo('lumi_who', 'lumi', '...who exactly were you stealing it for?', gap=0.7)
sheet.vo('both_him', 'both', 'Him.', gap=0.35)
sheet.fx('woof', gap=0.15)
# SCENE 11 — punchline
sheet.mark('s11', 0.8, gap=0.4)
sheet.fx('sigh')
sheet.fx('drawer', gap=0.1)
sheet.fx('shimmer2', name='shimmer', gap='@0.4')
sheet.mark('reveal', 1.4, gap='@0.0')
sheet.vo('pip_said', 'pip', '<prosody rate="85%">...you said it was the last one.</prosody>')
sheet.vo('milo_was', 'milo', 'It was the last one...', gap=0.35)
sheet.mark('milo_points_up', 0.7, gap=0.1)
sheet.vo('milo_shelf', 'milo', '...on that shelf.')
sheet.mark('lumi_stare', 0.9, gap=0.2)
sheet.vo('lumi_out', 'lumi', 'Get out.')
sheet.mark('black', 0.6, gap=0.3)
sheet.vo('pip_road', 'pip', 'Can I take one for the road?')
sheet.fx('thud_end', name='thud', gap=0.3)
sheet.vo('pip_ow', 'pip', 'Ow.', gap=0.3)
sheet.mark('end', 1.0)
